from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

import joblib

# Allow running from repo root or backend directory
BACKEND_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_DIR.parent
sys.path.insert(0, str(BACKEND_DIR))

from app.services.indicators import add_indicators  # noqa: E402
from app.services.market_data import DEFAULT_SYMBOLS, fetch_history, normalize_symbol  # noqa: E402
from app.services.predictor import HORIZONS, MODEL_DIR, _model_path, train_models_for_symbol  # noqa: E402
from app.services.daily_learning import prune_learning_data  # noqa: E402


def _default_symbols() -> list[str]:
    return [item["symbol"] for item in DEFAULT_SYMBOLS]


def _load_individual_package(symbol: str, horizon_key: str) -> Dict[str, Any] | None:
    path = _model_path(symbol, horizon_key)
    if not path.exists():
        return None
    try:
        return joblib.load(path)
    except Exception:
        return None


def build_model_pack(symbols: list[str], period: str, max_mb: float, keep_individual: bool = False) -> Dict[str, Any]:
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    trained_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    pack: Dict[str, Any] = {
        "version": "v9-free-stack-model-pack",
        "trained_at": trained_at,
        "period": period,
        "symbols": {},
        "errors": {},
        "note": "Generated by backend/scripts/train_model_pack.py. Intended for GitHub Actions/Kaggle training, not Koyeb runtime training.",
    }

    for raw in symbols:
        symbol = normalize_symbol(raw)
        try:
            history = fetch_history(symbol, period=period, interval="1d")
            enriched = add_indicators(history)

            market_enriched = None
            try:
                market_history = fetch_history("^NSEI", period=period, interval="1d")
                market_enriched = add_indicators(market_history)
            except Exception:
                market_enriched = None

            result = train_models_for_symbol(enriched, symbol, market_df=market_enriched)
            pack["symbols"][symbol] = {}
            for config in HORIZONS:
                pkg = _load_individual_package(symbol, config.key)
                if pkg:
                    pack["symbols"][symbol][config.key] = pkg
                else:
                    pack["symbols"][symbol][config.key] = {"trained": False, "error": (result.get("models") or {}).get(config.key)}
        except Exception as exc:  # noqa: BLE001
            pack["errors"][symbol] = str(exc)

    pack_path = MODEL_DIR / "model_pack.joblib"
    manifest_path = MODEL_DIR / "model_manifest.json"
    joblib.dump(pack, pack_path, compress=("xz", 3))
    size_mb = pack_path.stat().st_size / (1024 * 1024)

    manifest = {
        "version": pack["version"],
        "trained_at": trained_at,
        "period": period,
        "symbols_requested": symbols,
        "symbols_trained": sorted(pack["symbols"].keys()),
        "errors": pack["errors"],
        "model_pack_file": "model_pack.joblib",
        "model_pack_size_mb": round(size_mb, 2),
        "model_max_mb": max_mb,
        "free_limit_status": "ok" if size_mb <= max_mb else "too_large",
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    if not keep_individual:
        for joblib_file in MODEL_DIR.glob("*.joblib"):
            if joblib_file.name != "model_pack.joblib":
                try:
                    joblib_file.unlink()
                except OSError:
                    pass

    if size_mb > max_mb:
        raise RuntimeError(
            f"model_pack.joblib is {size_mb:.2f} MB, above limit {max_mb:.2f} MB. "
            "Reduce symbols, estimators, or training period."
        )

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Train compact deployment model pack for the AI NSE Stock Analyzer.")
    parser.add_argument("--symbols", default=os.getenv("TRAIN_SYMBOLS", ""), help="Comma-separated symbols. Blank uses default symbols.")
    parser.add_argument("--period", default=os.getenv("TRAIN_PERIOD", "5y"), help="Training period, for example 2y, 5y, max.")
    parser.add_argument("--max-mb", type=float, default=float(os.getenv("MODEL_MAX_MB", "95")), help="Maximum model pack size in MB.")
    parser.add_argument("--keep-individual", action="store_true", help="Keep individual per-symbol model files next to model_pack.joblib.")
    parser.add_argument("--skip-db-prune", action="store_true", help="Do not prune Neon/DB after training.")
    args = parser.parse_args()

    symbols = [s.strip() for s in args.symbols.split(",") if s.strip()] if args.symbols else _default_symbols()
    manifest = build_model_pack(symbols=symbols, period=args.period, max_mb=args.max_mb, keep_individual=args.keep_individual)
    print(json.dumps(manifest, indent=2))

    if not args.skip_db_prune:
        try:
            result = prune_learning_data()
            print("DB prune result:", json.dumps(result, indent=2))
        except Exception as exc:  # noqa: BLE001
            print(f"DB prune skipped/failed: {exc}")


if __name__ == "__main__":
    main()
